# Generated by Django 5.0.2 on 2024-07-19 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50)),
                ('device_creationTime', models.DateTimeField(auto_now_add=True)),
                ('device_voltage', models.IntegerField(max_length=3)),
                ('device_current', models.IntegerField(max_length=3)),
                ('device_owner', models.CharField(max_length=100)),
                ('device_phone', models.CharField(max_length=100)),
            ],
        ),
    ]
