# Generated by Django 5.0.2 on 2024-06-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataDump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.TextField(max_length=50, null=True)),
                ('y', models.TextField(max_length=50, null=True)),
            ],
        ),
    ]
