# Generated by Django 5.0.2 on 2024-06-29 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datadump',
            name='y',
        ),
    ]
