# Generated by Django 5.0.2 on 2024-07-19 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_datadump_y'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datadump',
            old_name='x',
            new_name='field1',
        ),
        migrations.AddField(
            model_name='datadump',
            name='field2',
            field=models.IntegerField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='datadump',
            name='field3',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
