# Generated by Django 5.0.2 on 2024-07-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_x_datadump_field1_datadump_field2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadump',
            name='field2',
            field=models.IntegerField(null=True),
        ),
    ]
