# Generated by Django 5.0.2 on 2024-07-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_description', models.CharField(max_length=200)),
                ('customer_state', models.CharField(max_length=50)),
                ('customer_city', models.CharField(max_length=50)),
                ('customer_zipcode', models.IntegerField()),
                ('customer_address', models.CharField(max_length=100)),
                ('customer_address2', models.CharField(max_length=100, null=True)),
                ('customer_phone', models.IntegerField()),
                ('customer_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
