# Generated by Django 5.0.2 on 2024-07-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_creationTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
