# Generated by Django 5.1.1 on 2024-09-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_customeruser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeruser',
            old_name='cuser_name',
            new_name='cuser_fname',
        ),
        migrations.AddField(
            model_name='customeruser',
            name='cuser_email',
            field=models.EmailField(default=False, max_length=254),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='cuser_lname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
