# Generated by Django 5.1.1 on 2024-09-18 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_cuser_name_customeruser_cuser_fname_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerUser',
        ),
    ]
